---
# for some reason docker_container and docker_service only work if docker and docker-compose
#  were installed through pip
- name: install pip3
  become: true
  apt: name={{item}} state=present
  with_items:
    - python3-dev
    - python3-setuptools
    - python3-pip

- name: Install Virtualenv
  become: true
  pip:
    name: "virtualenv"
    executable: pip3

- name: remove docker-py
  become: true
  pip:
    name: docker-py
    state: absent
    executable: pip3

- name: install docker with pip3
  become: true
  pip:
    name: docker
    executable: pip3

- name: install docker-compose with pip3
  become: true
  pip:
    name: docker-compose
    executable: pip3
