---
# for some reason docker_container and docker_service only work if docker and docker-compose
#  were installed through pip
- name: install pip
  become: true
  apt: name={{item}} state=present
  with_items:
    - python-pip
    - python-dev
    - python-setuptools

- name: Install Virtualenv
  become: true
  pip:
    name: "virtualenv"

- name: remove docker-py
  become: true
  pip:
    name: docker-py
    state: absent
  register: pip_result_handler #if this fails there was an error with pip
  ignore_errors: True
  notify: removed-docker-py

  #the following is just error handling becuase there are some messed pip version in the repos..
- name: remove pip
  become: True
  apt:
    name: python-pip
    state: absent
    purge: yes
  when: pip_result_handler is failed

- name: install pip through get-pip
  become: true
  command: curl https://bootstrap.pypa.io/get-pip.py | sudo python
  when: pip_result_handler is failed

- name: install pip through apt
  become: true
  apt:
    name: python-pip
    state: present
  when: pip_result_handler is failed

- name: install ssl_match_hostname with pip
  become: true
  pip:
    name: backports.ssl-match-hostname>=3.7.0

- name: install ssl_match_hostname with pip
  become: true
  pip:
    name: backports.ssl-match-hostname>=3.7.0
    virtualenv: "{{ docker_pip_virtualenv }}"

- name: remove docker-py
  become: true
  pip:
    name: docker-py
    state: absent
  notify: removed-docker-py

- name: install docker with pip
  become: true
  pip:
    name: docker
    virtualenv: "{{ docker_pip_virtualenv }}"
  register: docker_pip_result
  ignore_errors: True

#this resolves https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteready
#(try to install with pip after that again)
- name: clear python 2.7 requests
  become: true
  command: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
  when: docker_pip_result is failed

- name: install docker with pip
  become: true
  pip:
    name: docker
    virtualenv: "{{ docker_pip_virtualenv }}"
  when: docker_pip_result is failed

- name: Symlink Python binary to /usr/local/bin/python-docker
  become: true
  file:
    path: "/usr/local/bin/python-docker"
    src: "{{ docker_pip_virtualenv }}/bin/python"
    force: true
    state: "link"

# docker-compose and docker python must be within different virtual python envs!
- name: install docker-compose with pip
  become: true
  pip:
    name: docker-compose
  register: docker_compose_pip_result
  ignore_errors: True

#this resolves https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteready
#(try to install with pip after that again)
- name: clear python 2.7 requests
  become: true
  command: rm -rf /usr/local/lib/python2.7/dist-packages/requests*
  when: docker_compose_pip_result is failed

- name: try to install docker-compose with pip again
  become: true
  pip:
    name: docker-compose
  when: docker_compose_pip_result is failed
