---
#tasks file for role

- name: Get System
  become: true
  command: uname -s
  register: command_system
  changed_when: command_system.stdout != 'Linux'

- name: Get Environment
  become: true
  command: uname -m
  register: command_env
  changed_when: command_env.stdout != 'x86_64'

- name: Download docker compose executable
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ command_system.stdout }}-{{ command_env.stdout }}
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: install backports.ssl-match-hostname to be able to call docker-compose
  become: true
  apt:
    name: python-backports.ssl-match-hostname
    state: present
  when: (ansible_python_interpreter is undefined) or not (ansible_python_interpreter is search("python3"))

- name: Get current docker-compose version
  become: true
  command: docker-compose --version
  register: command_docker_compose_version
  changed_when: not command_docker_compose_version.stdout is match('docker-compose version .*')

- name: Force download of docker compose executable to get the defined version
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ command_system.stdout }}-{{ command_env.stdout }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
    force: yes
  when: not command_docker_compose_version.stdout is match('docker-compose version ' + docker_compose_version + '.*')
